### ISSUE TITLE
Return array from render function?

### ISSUE THREAD

**Issue by rill-js** [dekujs/deku#107]
Has anyone considered support for returning multiple elements from a render function to avoid excess html?

Such as:

```javascript
function render (component) {
    return [
        element('a', { class: "button" }, ["hello"]),
        element('a', { class: "button2" }, ["world"])
    ]
}
```

**Comment by anthonyshort** [comment]
I'm curious as to why this would be useful other than just have fewer elements? It could be possible but I think it would add a bit of complexity to the way we map elements to instances of the components. If there's a solid use-case for it then we can definitely look into it!

**Comment by rill-js** [comment]
I wasn't sure of the complexity of this request, however for myself it just makes it easier to convert html projects to the virtual DOM. Often it breaks styles when <div> is added for each component to satisfy the virtual dom.

**Comment by lancejpollard** [comment]
@rill-js the reason this isn't implemented currently is because it changes the way the diffing works in a fundamental way. It's definitely possible, and would be cool to make it work like that, it would just take a good amount of time thinking through how to support both one/many "virtual trees" in the renderer. Basically this would need to be rethought:

https://github.com/segmentio/deku/blob/master/lib/render.js#L356-L364

Removing some of the code, the gist of that method is essentially this:

```js
function updateEntity (entityId) {
  var entity = entities[entityId]
  var currentTree = entity.virtualElement
  var nextProps = entity.pendingProps
  var nextState = entity.pendingState
  var previousState = entity.context.state
  var previousProps = entity.context.props
  var nextTree = entity.component.render(entity.context, setState(entity))
  if (nextTree === currentTree) return updateChildren(entityId)
  entity.nativeElement = patch(entityId, currentTree, nextTree, entity.nativeElement)
  entity.virtualElement = nextTree
}
```

In order for that to support arrays, the "entity" would need to be generalized to support arrays somehow, where the default/common case of single objects would maybe mean a 1-item array. The entity is basically just the data structure used to keep track of all the component instance rendering info.

That's definitely possible, but to us it seemed like it would take a lot of thought and consideration to handle correctly, and it might be a lot of work (which we can spend doing other stuff). So we just made the tradeoff and went with the convention "just have `render` always return a single object instead of an array".

Would be really cool though to have that, just we probably won't personally add that in the near future for those reasons. Does that help?

**Comment by anthonyshort** [comment]
I haven't looked into it too much, but using Ranges could potentially make this possible. We'd be able to keep a set of nodes and use them like a fragment, be we can insert and move the entire range. 

It wouldn't work in IE though. But it could be a really interesting thing to try out

**Comment by carlosdubus** [comment]
What if you create a special entity that acts like a normal element but instead of rendering itself, it only renders its children?

```js
function render (component) {
    return element('container',
        element('a', { class: "button" }, ["hello"]),
        element('a', { class: "button2" }, ["world"])
    );
}

**Comment by anthonyshort** [comment]
That's basically just like using a document fragment, it would be really similar to that but fragments aren't kept around. That's not a bad idea, but it would be kind of a weird abstraction. Maybe we could just export something like

```
import {fragment} from 'deku'
```

then you could use that. Not too sure if we need multiple returns yet. If it's for CSS reasons then I'd argue that the CSS is touching more than it should be anyway.
