### ISSUE TITLE
Element isn't in the document in afterMount

### ISSUE THREAD

**Issue by staygrimm** [dekujs/deku#108]
Say I have the following component, which is being called from a parent component:

```js
import {element} from 'deku'

export function render (component) {
  let {props, state} = component
  return (<div id='foo'>Hello World</div>)
}

export function afterMount (component, el) {
  console.log(document.getElementById('foo')) //=> returns null
}

export default {render, afterMount}
```

I would have expected `console.log(document.getElementById('foo'))` to return the element, according to the docs.  Am I misunderstanding that the element should be located in the dom by the time afterMount is called?

My specific intention is to do some manipulation once the component's element has been inserted in the dom.

**Comment by anthonyshort** [comment]
What's the use case for it needing to be within the DOM instead of just touching the element itself? Calculating layout?

**Comment by anthonyshort** [comment]
That said, I'd say this is a bug and isn't working as it was intended :)

**Comment by staygrimm** [comment]
I'm actually trying to use a 3rd party lib that unfortunately doesn't take an element on initialization, I have to pass it an id or class name in an options object and it then searches the dom.

**Comment by anthonyshort** [comment]
I'll take a look at this tomorrow, it hopefully won't be too hard to fix up. A temporary hack might be to use `requestAnimationFrame` in `afterMount` to wait until the next frame when it'll be in the DOM.

For reference, it gets called here https://github.com/segmentio/deku/blob/master/lib/render.js#L208, which is just being called straight after the element is created, but before it's insert into the DOM. This is because it can be created in multiple ways (initial mount, during the diff, nodes being replaced).
