### ISSUE TITLE
Element needs a type

### ISSUE THREAD

**Issue by dagda1** [dekujs/deku#123]
I am trying to get a simple example working.

Everything works if I have all the components in the same file but I am having trouble when using es6 modules, jsx and babel and importing components from different files:

For example if I have an ```App``` Component in an ```app.js``` file:
```
import {element} from 'deku';

export function render (component) {
  let {props,state} = component

  return (
    <div class="App">
      <h1>My App</h1>
    </div>
  )
}
```
If I then try and import this in my ```index.js``` file:
```
import App from './app';
import {element,render,tree} from 'deku';

var app = tree(<App />)

render(app, document.body);
```
I get the following error:
```
Element needs a type
```
Which is an assertion being ran here:
```
function virtual (type, props, children) {
  // Default to div with no args
  if (!type) {
    throw new Error('Element needs a type. https://gist.github.com/anthonyshort/77ced43b5defe39908af')
  }
```
```type``` is undefined, so the export is not happening for some reason.

All the files are in the same directory and I use browserify to do do the transform with the following entry in my ```makefile```:
```
build.js: node_modules $(js)
	node_modules/browserify/bin/cmd.js -t babelify --debug src/index.js > build.js
```

**Comment by stevenmiller888** [comment]
Hey @dagda1 - Try changing your `app.js` file to the following:

```
/** @jsx dom */

import {dom} from 'deku';

function render (component) {
  let {props,state} = component;

  return (
    <div class="App">
      <h1>My App</h1>
    </div>
  )
}

export default {render}
```

Notice that we added `/** @jsx dom */` to the top to indicate that this is JSX. We're also now exporting a default function, since you're importing it with `import App from './app';`. You could also use `export {render}` and  `import * as App from './app';`. Finally, we're importing `{dom}` rather than `{element}`. @anthonyshort any idea why it fails with `{element}`?

Let me know if that helps.

**Comment by anthonyshort** [comment]
That's a common problem people have with ES6 modules. Given your example:

```js
import {element} from 'deku';

export function render (component) {
  let {props,state} = component

  return (
    <div class="App">
      <h1>My App</h1>
    </div>
  )
}
```

This module does export anything by `default`, so when you do this:

```
import App from './app'
```

There's nothing to import, so Babel will just evaluate that as `undefined` rather than throwing an error. To import what you've given, you'd need to do this:

```
import {render} from './app'
```

since render is the only thing you're exporting. But what I'm guessing you're looking to do is this:

```js
import {element} from 'deku';

function render (component) {
  let {props,state} = component

  return (
    <div class="App">
      <h1>My App</h1>
    </div>
  )
}

export default {render}
```

This allows you to import this module like this:

```
import App from './app'
```

And you'll get this object:

```
{
  render: fn
}
```

Which is a valid component. Hope that helps! ES6 modules can be confusing like that, but if you've used commonjs before, you can think of `default` being `module.exports` and everything else just being put onto `exports`.

**Comment by dagda1** [comment]
Changing the export to ```{ render }``` fixes things, thanks.

I was following the examples from this repo and they all follow the form:
```
export function render () {
```
Maybe this is how the es6 modules previously worked?

**Comment by anthonyshort** [comment]
I've just updated the examples to make sure they're using the right syntax :)
