### ISSUE TITLE
Plugins examples and docs

### ISSUE THREAD

**Issue by scottcorgan** [dekujs/deku#155]
I'm note sure I follow when it comes to using and implementing plugins. Are there docs or examples of a plugin and how it's used with a component?

**Comment by lancejpollard** [comment]
@scottcorgan sorry haha, yeah these aren't documented at all. We've only used them in basic ways ourselves, but are starting to play with other ways.

## Basic Plugins

As a temporary doc, here's a basic example of how it works:

```js

import {deku,render} from 'dekujs/deku'

let App = {
  render() {
    return <div>hello world</div>
  }
}

deku(<App/>)
  .use(rendering)

function rendering(app) {
  render(app, document.body)
}
```

Basically, plugins are just modules that expose a single function by convention. The function just takes in the `app`, and can do whatever it wants to it. It's like the koa/express/etc. convention, but here `.use` literally just executes the function immediately, just api sugar.

https://github.com/dekujs/deku/blob/master/lib/application.js#L38

```js
Application.prototype.use = function (plugin) {
  plugin(this)
  return this
}
```

That other issue about routing has a more robust example with a few plugins:

https://github.com/dekujs/deku/issues/149#issuecomment-108109463

## Plugins with Components

By convention also, we started messing around with "component" plugins. In that issue linked to above you see this:

```js
deku(<App/>)
  .use(components)
```

That was a random plugin I probably should've left out, was just playing around with different ways. It looks like this:

```js
import Dialog from '../dialog'
import Popup from '../popup'

export default function(app) {
  app.use(Dialog.register)
  app.use(Popup.register)
}
```

The `Dialog` and `Popup` are weird components because you want to _create_ them locally a lot of the time (from on click in some deeply nested dom element), but you want them to render globally. So a popup might look like this:

```js
/**
 * Module dependencies.
 */

import offset from 'timoxley/offset'
import {dom} from 'dekujs/deku'

/**
 * Global hook.
 */

export function register(app) {
  app.set('openPopup', function(popup){
    app.set('clickHandler', close)
    app.set('currentPopup', popup)

    function close() {
      app.set('currentPopup', null)
      app.set('clickHandler', null)
    }
  })
}

/**
 * Render.
 */

export function render({props}) {
  let {position, anchor, children} = props
  if (position instanceof window.Event) {
    position = offset(position.target)
  }
  anchor = anchor || 'top-left'

  let style = { position: 'absolute' }
  switch (anchor) {
    case 'top-left':
      style.left = position.left + 'px'
      style.top = position.top + 'px'
      break;
    case 'bottom-left':
      style.left = position.left + 'px'
      style.top = position.top - 60 + 'px'
      break;
  }

  return <div class='Popup' style={style}>
    {children}
  </div>
}
```

The main part of the popup relevant here is the `register` function, which is called in the `components` plugin above (by convention, just playing around right now, trying to find what works).

You then can _create_ a popup like this in some random component that opens a popup:

```js

/**
 * Module dependencies.
 */

import {dom} from 'dekujs/deku'

/**
 * Define properties.
 */

export const propTypes = {
  open: { source: 'openPopup' }
}

/**
 * Render.
 *
 * This is just a random component, say it's like a settings icon that
 * pops up with some content on click.
 */

export function render({props}) {
  let {open} = props
  return (
    <div onClick={onClick}>Open popup!</div>
  )

  function onClick(event) {
    open(<Popup position={event} anchor='top-left'>
      <div>Some popup content</div>
    </Popup>)
  }
}
```

So that's for creating the popup. It calls `open`, which is defined on the app as `openPopup`. (Naming it `open` is arbitrary, just showing it can be named differently). And that `openPopup` was defined in the popup components' `register` function earlier, which was added as a plugin to the app in the `components` plugin, which is just a wrapper for all these random components with plugins to clean things up :)

To finish the cycle, `openPopup` calls `app.set('currentPopup', popup)`, which will trigger a re-render on the app b/c of the app property `popup` below, which receives it value from the global data source `currentPopup`:

```js
export const propTypes = {
  popup: { source: 'currentPopup' }
}

export function render({props}) {
  let {popup} = props
  return <div>
    Some content...
    {popup}
  </div>
}
```

So with these "component plugins", basically it's just some way to get access to the app, so that they can pass messages around ("set data sources" or "invoke actions").

Hopefully this answers your question, let me know if anything's still unclear :)

**Comment by lancejpollard** [comment]
In case I missed the last part of your question, you don't use plugins _with_ a component, plugins are only used on the app. It's just that some components like the popup need to do some global stuff, so that convention of the `register` function on the component makes it so there's some relation between apps/components/plugins.

**Comment by scottcorgan** [comment]
Very detailed, appreciate that. Good documentation to have.
