### ISSUE TITLE
Async data for isomorphic apps.

### ISSUE THREAD

**Issue by DylanPiercey** [dekujs/deku#161]
Is there anyway to wait for the initial promise of afterMount (similar to react-async)?

I understand that the rendering process (at least in most vdom libs) is designed to synchronous but I have yet to find a good solution to pre-load data on the server.

Flux works okay (with fluxible or others) but it would make for a more simplistic api on the server if the server could simply wait for afterMount rather than having to abstract out data that only one component may use into a store.

How are all of you handling this? Sorry that it's not really specific to deku, but i'd like to know the best way to handle async server side rendering with deku.

**Comment by anthonyshort** [comment]
Yeah the rendering needs to be synchronous. It sounds like something that should be given a specific hook. But I don't really like the idea of components handling fetching of data too. Fetching should really happen outside of Deku and your components. It will make them way easier to reason about if they just get passed everything in via props.

The way I've been thinking about it lately is that your UI is just a snapshot at a point in time. A combination between a tree of components and a fixed set of data. The `tree` allows you to set this data and access it from components so you don't need to do the fetching in the component itself. 

This makes server rendering easier too. On both the client and server you just fetch everything you need, however you need to do that, and then render the UI using all that data.

However, one nice thing about keeping the logic inside of the component itself is that data dependencies are also defined where they're used (like Relay/GraphQL). Last time I checked, React was looking at adding an `observe` hook to allow observables to be bound to props. I don't like this approach because you're couple **how** the data is loaded, instead of just **what** data is needed.

Because components are just objects you could just ask components to declare what data they need and you can use the virtual tree to then wrap up all dependencies and inject them where needed. As far as I know, this is how Relay works.

```
export let query = {
  // declare data dependencies somehow...
}
```

We've got the basic method of just calling `app.set()` to access data from components without them knowing where that data came from. We don't really have problems with over-fetching and we don't really care about optimizing exactly what data is returned from the server because it has such small gains for most apps. Once you're at Facebook size or you're dealing with some mobile app with lots of various, deeply nested data models you can probably get away with the simple solution.

Anyway, my point is, I like the idea of fetching all data and then using that to render the app all at once. Loading states can easily be handled by `null` values. I'm curious to see if anyone can take this to the next level and create something to handle all of these advanced use-cases too.

**Comment by DylanPiercey** [comment]
Thanks for the insight, messing around with deku more now to see if I can solve this problem!

**Comment by DylanPiercey** [comment]
Closing this since its not really an issue with deku.
