### ISSUE TITLE
Uncontrolled inputs.

### ISSUE THREAD

**Issue by DylanPiercey** [dekujs/deku#163]
Currently uncontrolled inputs (One's that aren't linked to state) are re-rendered on every update.
Below when the "Toggle" button is clicked it will also clear the text input. React doesn't act this way and I'm wondering if there is a way around it without explicitly controlling the inputs state?

```javascript
Home = {
  getInitialState: function() {
    return {};
  },
  handleClick: function(e, component, setState) {
    var state = component.state;
    return setState({
      clicked: !state.clicked
    });
  },
  render: function(arg) {
    var props, state;
    props = arg.props, state = arg.state;
    <main>
        { state.clicked ? <div>Clicked</div> : undefined }
        <button onClick={ Home.handleClick }>Toggle</button>
        <input type="text"/>
    </main>
  }
};
```

Seems to happen when the order of elements gets moved around (Maybe internally the child list is flattened?)

**Comment by anthonyshort** [comment]
Yeah this was something we were messing around with recently and something we deliberately did different. The only reason we didn't make it similar to React is that we've never run into a case where this didn't work for us.

In this case, the way the diffing works, is that it ignores `undefined` or `null` elements. So it's like it's not even there, meaning that when the div exists, the indexes all shift and they're replacing the HTML elements. Because the DOM keeps state you lose the value the user added. 

To get around this you can either:

1. Not use `undefined`, and instead use a `<noscript />` or similar.
2. Just hide the div instead of removing it
3. Make the input a component and use the `key` attribute so the state is kept around (we don't yet support keys on elements, only on components).

Hope that helps!

**Comment by DylanPiercey** [comment]
That helps, that's what I thought was happening. Works fine without nullish elements. I am curious though, what is the benefit of ignoring null items as children? Seems like it would be convenient to keep them simply for child indexes.

**Comment by anthonyshort** [comment]
That's a good point. I mainly use it so that I can just easily show and hide elements conditionally:

```js
let sheet = null;
if (thereShouldBeASheet) {
  sheet = <Sheet />
}

return <div>{sheet}</div>
```

But that could easily be done another way. What would you expect the falsy values to look like? Just empty strings?

**Comment by DylanPiercey** [comment]
Not 100% on the internals of deku, but I would guess that an nullish value when diffed would simply act as a removeChild operation.

**Comment by anthonyshort** [comment]
> Not 100% on the internals of deku, but I would guess that an nullish value when diffed would simply act as a removeChild operation.

Yeah this is how it works. If a virtual node is seen on the left, but on the right the value is `undefined`, it's treated as a removal. However, when rendering virtual elements, any `null` children are removed before the diff. This is creating the weird behaviour you're seeing (and others have brought up).

We could just keep `null` elements in there and render them as empty strings potentially. We'd need to do this because the diff looks for the real DOM elements via the index. So if the children looked like this:

````
[
  null,
  <div />
  <div />
]
```

But the real children looked like this:

```html
<div></div>
<div></div>
```

Then when using the indexes it would be wrong. We could either be tricky with this and shift the index, or we could just render a `<noscript/>` for `null` values so nothing renders.

**Comment by DylanPiercey** [comment]
@anthonyshort was this resolved?
