### ISSUE TITLE
Investigate compatibility between deku element and virtual-dom hyperscript

### ISSUE THREAD

**Issue by bitinn** [dekujs/deku#164]
For curiosity I would like to try out `deku` on one of my personal project. I already had a fully working MV system (as well as server-side rendering) based on `virtual-dom`.  I would like to see if we can just substitute virtual-dom's `h` with deku `element`.

Appreciate any heads-up on known incompatible features :)

I expect some problem with my svg icons solution given current svg namespace support appear to be incomplete, eg: `xlink:href`

- https://github.com/dekujs/deku/blob/master/lib/svg.js
- https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/svg-attribute-namespace.js

**Comment by anthonyshort** [comment]
Hey @bitinn! Glad you're interested in checking it out. The syntax for the virtual elements between the two libraries should be the same, the main difference will be the way it handles components. `virtual-dom` doesn't have the concept of components, like this:

```
h(MyComponentObject, { one: 'two' }, ['Hello!'])
```

But Deku does. Originally we wanted to just use virtual-dom for Deku but it's too different in it's approach. I'd still like to just use the same library at some point instead of having our own. It increases the project scope more than it should. 

Apart from that I think everything else should be the same. 

As for SVG support, if we're missing anything, you can open a PR with any SVG attributes we're missing. I'm not an SVG pro so I might have missed a few things.

**Comment by bitinn** [comment]
Thx. Another point is progressive enhancement: where you attempt to reconcile virtual dom with server-rendered dom by generating a vdom from real dom, and diff it against client-side rendered vdom to create a smaller patch (than re-render the whole doc).

I will need to port [vdom-virtualize](https://github.com/marcelklehr/vdom-virtualize) to support deku.

PS: https://github.com/crysalead-js/dom-layer is probably the only one that comes with this implementation in core.

**Comment by bitinn** [comment]
As part of my investigation, I wrote this: https://gist.github.com/bitinn/ca83c32f041f89e4e5ad

It abstracts both `virtual-dom` and `deku` api into a single `vdom` function. so i don't have to change anything in my `virtual-dom` templates to use `deku` for server-rendering.

In longterm, I think unifying api between different vdom module will be very useful, especially for those don't want to use JSX.

PS: surprisingly in my test svg elements works, so I guess deku doesn't care about foreign namespace (for attributes like `xlink:href`, which is outside of default namespace)?

**Comment by anthonyshort** [comment]
Definitely agree on that. It would mean swapping out rendering libraries easy, JSX would work for everything with a single transformer, and it would remove the coupling of the vdom module from the library. That would mean components wouldn't have a peer dependency on Deku which would be a big win for sharing components.

Even just having a "spec" for what a virtual element looks like that works for all the use cases people are using it for. It could just be something like:

```
VirtualElement {
  type: String | Object | Function
  attributes: Object
  children: Array | String
  key: String
  ref: String
  namespace: String
}

VirtualText {
  data: String
  key: String
  ref: String
}
```

Then everyone could use a single module for virtual nodes and potentially use different modules for diffing and patching depending on their implementation. 

@Matt-Esch @crysalead-js, what do you think? It would be awesome if all the different vdom libraries became just one (at least for creating the elements). I think they all have some unique points of view and interesting use-cases.

**Comment by jails** [comment]
Sorry, I didn't get the notification, I just randomly stumbled on that discussion. So before I started to create `dom-layer` I tried to find a kind of "universal representation" of virtual elements. But the only thing I found was https://github.com/gcanti/uvdom, and after some experimentations I realized that it wasn't generic enough.

Indeed it's a difficult task to find the perfect "universal representation" but imo the virtual dom layer should provide at least a way:
- to manage DOM events
- to be able to run some `callbacks` when a node has been created, updated or removed
- to deal with DOM element props. Due to some DOM "awkwardness" it's not always possible to rely only on DOM element attributes (ex: http://www.w3schools.com/tags/av_prop_muted.asp).
- to be able to store some custom data required for a higher level of abstraction

So I finally decided to craft my own https://github.com/crysalead-js/dom-layer/blob/master/src/node/tag.js#L18-L35 to make it the most generic possible and I decided to let the "end-coder" to write his own transformer function (a.k.a the [hyperscript function](https://github.com/Matt-Esch/virtual-dom/tree/master/virtual-hyperscript)) according to its need or feature requirements.

Just quickly looked at the `dekujs` source code and I think the main issue wouldn't rely on the virtual element representation but on how `Components` are recursively mounted and how `*Mount` event are triggered.

I designed `dom-layer` to fit my needs related to a custom higher abstraction but if you have some questions about `dom-layer`, how it can be used in a specific context, or for a custom need feel free to ask.
