### ISSUE TITLE
Input `onInput` event diff issue?

### ISSUE THREAD

**Issue by daryl** [dekujs/deku#170]
I'm trying to validate user input on the fly and only allow certain characters.

Check out [this](http://requirebin.com/?gist=9fac095f0288cd165270) RequireBin.

On the first change it will apply the `idk` value, after that it does nothing.

However if you changed the state update to this:

```js
next({value: Math.random()*215235, count: state.count+1});
```
It will apply each time.

**Comment by anthonyshort** [comment]
The DOM storing state can be annoying like this. We're not updating the `value` property of the element because the state value hasn't actually changed: https://github.com/dekujs/deku/blob/master/lib/render.js#L666

We skip setting attributes that have the same previous value because it slows down the rendering to touch the DOM at all. We either need to make an exception for the value attribute or just check the actual value of the element and compare that.

We could also go the same route as React with controlled components.
