### ISSUE TITLE
onWheel event

### ISSUE THREAD

**Issue by foray1010** [dekujs/deku#171]
I think as deku only support legacy browsers, supporting 'wheel' event is a good idea.
If some old browsers are concerned, we can use mousewheel event for them.

lib/events.js
>onWheel: window.onmousewheel && !window.onwheel ? 'mousewheel' : 'wheel'

**Comment by anthonyshort** [comment]
Sounds great. I haven't used this event in a while, so we probably missed it. If you want to open a PR I'll merge it in. It should just be adding it here: https://github.com/dekujs/deku/blob/master/lib/events.js

I wouldn't even bother with `onmousewheel`, since `wheel` is supported in IE9+ and everything else. Might as well leave out code we don't need :)
