### ISSUE TITLE
Component lifecycle hooks arguments consistency

### ISSUE THREAD

**Issue by Yomguithereal** [dekujs/deku#183]
Hello deku! According to you documentation, the render method take a "component" object as argument which is basically an object containing the component's props and state. Wouldn't it be more consistent and easier to pass prevComponent or nextComponent in a similar fashion to lifecycle hook rather than separating props and state in said functions?

```js
function render(component) {
  const {props, state} = component;
}

// Lifecycle hooks work thusly:
function afterUpdate(component, prevProps, prevState, setState) {

} 

// Wouldn't the following be better?
function afterUpdate(component, prevComponent, setState) {
  const {prevProps, prevState} = prevComponent; 
}
```

Sorry if this has already been mentioned and I unfortunately missed it.

**Comment by anthonyshort** [comment]
Ah! I thought about this. The reason we didn't do this was because the `component` could actually contain more properties, like `context`, `el` or `updateState`. This isn't needed for the previous component, or maybe it doesn't exist.

This means the component always has the same properties. It would be confusing if you could access one thing on the left, and another on the right. We chose to be more explicit about that for those hooks.

Sidebar: I'm also trying to figure out all of the use cases for those hooks. Ideally they don't even need to exist... so I'm interested to learn what you're using them for?

**Comment by Yomguithereal** [comment]
Fair enough. I thought it was not done thusly for reasons of this kind.

I am afraid I don't have many edgy use cases to report since I haven't tried much with the library yet. But basically I am searching for a less verbose, cleaner and simpler "reactey" view engine that you seem to provide quite well with this library.

My typical use cases for said hooks are:

1. On mount, bind components to an event emitter (typically those of [this](https://github.com/Yomguithereal/baobab) library) to refresh the component when my centralized app's state updates. And of course unbind listeners on unmount.
2. Sometimes I need to refresh the bindings of the event emitter when props updates, so I need to be able to track when props changes. `afterUpdate` is probably the correct hook to do that.
3. Using a persistent and immutable data structure, I need the `shouldUpdate` hook to perform shallow equality on props and state so I can skip rendering if I don't need to for performance reasons.
4. I often need to deploy editors such as [CodeMirror](https://codemirror.net/) and for this, the `afterMount` hook is necessary.
