### ISSUE TITLE
Keep a listener reference

### ISSUE THREAD

**Issue by troch** [dekujs/deku#193]
Hi,

Let's say I want to add a listener in `afterMount` and remove it in `beforeUnmount`, is it best practice to  keep a reference of the listener function on the component object?

```javascript
function afterMount(component, el, setState) {
    let listener = function (...) { ... }
    window.addEventListener('resize', listener)
    component.resizeListener = listener
}

function beforeUnmount(component, el) {
    window.removeEventListener('resize', component.resizeListener)
}
```

**Comment by anthonyshort** [comment]
The `component` object isn't guaranteed to be the same object each render (this is so we can memoize the render function). By, you do have the component id:

```js
var listeners = {}

function afterMount(component, el, setState) {
    let listener = function (...) { ... }
    window.addEventListener('resize', listener) 
    listeners[component.id] = listener
}

function beforeUnmount(component, el) {
    window.removeEventListener('resize', listeners[component.id])
    delete listeners[component.id]
}
```

It's not perfect, but since we're dealing with global DOM state here there's no real way to isolate the state unless you have a single resize listener at the root and set the values you need at the root and pass them down:

```js
function onResize (e) {
  render(<App width={window.clientWidth} height={window.clientHeight} />)
}
```

That would be just treat it like any other data source you have.

**Comment by troch** [comment]
:thumbsup: Thanks for your answer.

**Comment by pho3nixf1re** [comment]
I came across this while looking for an answer to something else and thought I would leave my solution to this. I just store the listeners in the state as a single object. Then you don't have to worry about manually cleaning up an unmanaged variable.
