### ISSUE TITLE
Sync setState

### ISSUE THREAD

**Issue by anthonyshort** [dekujs/deku#205]
Need to investigate this... Just recording it so I don't forget.

https://github.com/facebook/react/pull/629
https://github.com/dekujs/deku/issues/41#issuecomment-121985487

**Comment by ivan-kleshnin** [comment]
> I'm not sure I'm following the exact reasoning behind it yet though. What are the benefits to it? We don't access state on this so it probably wouldn't update the state object that gets passed in anyway.

The main benefit is that code is synchronous. `this.state` is always the "latest" state. It's obviously easier to work with sync code, than with async. No callbacks. No promises. Easier to reason about it. You can `setState()` multiple time which is often required when we refactor business logic into functions. No rigid hooks.

Now you can fire `setState` once, then you can analize it in `afterRender` once. 
What if we want to change something after analysis? No way, right?!

Will you excuse me, if I just give you a link to a thread where we had a lot of dissussion on this subject
https://github.com/Yomguithereal/baobab/issues/190 (starting from the 3-rd post from the top) 
There are more links to more discussions on this subject from different people. Don't want to copy-paste all that here. 

Basically, this very change was discussed and successfully implemented in the Baobab library and everyone seems to be happy about it. The context was slightly different, but I'm pretty sure this argumentation applies to Deku as well.

**Comment by ivan-kleshnin** [comment]
It seems, noone ever did find a single counter-arguments except backward compatibility.

**Comment by Mustack** [comment]
I have a related problem. I'm trying to test my component and having trouble with its state. My component uses `setState()` in `afterMount()` and my `beforeUnmount()` depends on that state. I've tried setting batching off (app.options.batching = false) but because `isRendering` is still true in the `afterMount()` hook, it still doesn't force a render right away.

This is the gist of my test.

``` javascript
app.mount(<Component/>);
render(app, document.body);

expect(spy.called).to.equal(false);
app.unmount();
expect(spy.called).to.equal(true);
```

The spy is a function that is the thing that is put in the state in `afterMount()` and then referenced in `beforeUnmount()`. This is testing that the function is called when the component is unmounted.
