### ISSUE TITLE
Is 0.5.0 stable enough to upgrade?

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#224]
I see a couple of breaking changes in `0.5.0` like moving virtual-element into separate module. Is it safe to upgrade, any breaking changes?

**Comment by anthonyshort** [comment]
The main breaking change is that `dom` isn't exposed anymore because Deku renders really generic virtual elements. The rest of the functionality is still there though. Here's the original PR for it: https://github.com/dekujs/deku/pull/217 

You can use https://github.com/dekujs/magic-virtual-element as a replacement for `dom` and everything should work the same as before.

**Comment by anthonyshort** [comment]
There are issues if you're trying to load components written using `0.4.0` that are using the `dom` module. You'll need to update those components to use `0.5.0`.
