### ISSUE TITLE
calling setState in onInput handler should trigger render call but does not

### ISSUE THREAD

**Issue by ndhoule** [dekujs/deku#226]
Calling `setState` inside of an `onInput` handler doesn't trigger a rerender.

An example, where `SearchBar` is an `input` that accepts text content:

```js
let handleUserInput = function(event, _, setState) {
  setState({
    filterText: event.target.value || ''
  });
};

let FilterableList = {
  render({ props, state }) {
    debugger;
    return (
      <div>
        <SearchBar
          filterText={ state.filterText }
          onInput={ handleUserInput }
        />
        <IntegrationList
          integrations={ props.integrations }
          filterText = { state.filterText }
        />
      </div>
    );
  }
};
```

I've confirmed that the content of the text box changes every time. Using Deku 0.5.0.

**Comment by anthonyshort** [comment]
I think I know what the problem is here. Because you're just passing in a function to `onInput`, it's going to be passed the `setState` for the `SearchBar` component, not the parent component like you're expecting. You'd either need to pass in the `setState` function for the parent component:

```jsx
<SearchBar
    filterText={ state.filterText }
    onInput={ handleUserInput(setState) }
/>
```

or you should just add a prop for when the filter changes:

```jsx
<SearchBar
   filterText={ state.filterText }
   onFilter={ filterText => setState({ filterText }) }
/>
```
```jsx
<input onInput={ e => props.onFilter(e.target.value) } />
```
